schema_version: 1

context:
  version: "0.8.4"

package:
  name: tavily-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tavily-python/tavily_python-${{ version }}.tar.gz
  sha256: 8031fd435e1c9580b7846044f456fc1d14b9c42b715740b3f0643a6e483abf83

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - requests
    - tiktoken >=0.5.1
    - httpx

tests:
  - python:
      python_version:
        - ${{ python_min }}
        - '*'
      imports:
        - tavily
      pip_check: true

about:
  summary: Python wrapper for the Tavily API
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tavily-ai/tavily-python

extra:
  recipe-maintainers:
    - xhochy
